# Reference:
# https://www.gitpod.io/docs/introduction/learn-gitpod/gitpod-yaml

tasks:
  - init: cargo build
    command: cargo watch -x test

vscode:
  extensions:
    - rust-lang.rust-analyzer

image:
  file: .gitpod.Dockerfile
